name: Build and Deploy Quarto

on:
  push:
    paths:
      - "day1_exercise_answers.qmd"
      - "day1_walkthrough_answers.qmd"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    
    - name: Restore R package cache
      uses: r-lib/actions/cache@v2
      with:
        path: renv/cache
        key: ${{ runner.os }}-r-${{ hashFiles('renv.lock') }}
    
    - name: Install dependencies with renv
      run: Rscript -e 'renv::restore()'
    
    - name: Install Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.340/quarto-1.3.340-linux-amd64.deb
        sudo dpkg -i quarto-1.3.340-linux-amd64.deb
    
    - name: Render Quarto files to HTML
      run: |
        quarto render your_specified_files/*.qmd
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Ensure your build outputs are placed here
        keep_files: true
